// Generated by CoughSyrup 0.0.0
(function() {
  var connectPortsToBuses, connectViewToController;

  connectPortsToBuses = require('./connectPortsToBuses.js');

  connectViewToController = require('./pando-adapter.js');

  module.exports = {
    connectPortsToBuses: connectPortsToBuses,
    connectViewToController: connectViewToController
  };

}).call(this);
